import Head from "next/head";
import { WishListRouter } from "~/components/WishList/WishListDetail";

export default function Home() {
  return (
    <>
      <Head>
        <title>Giftly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <WishListRouter />
      </main>
    </>
  );
}
