import Head from "next/head";
import { Layout } from "~/components/Layout";
import { PrivateWishListRouter } from "~/components/WishList/PrivateWishListRouter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Giftly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PrivateWishListRouter />
      </Layout>
    </>
  );
}
