import React from "react";
import { PublicTokenRouter } from "~/components/Token/PublicTokenRouter";
import { Layout } from "~/components/Layout";
import Head from "next/head";

export default function Public() {
  return (
    <>
      <Head>
        <title>Giftly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PublicTokenRouter />
      </Layout>
    </>
  );
}
